### ISSUE TITLE
BE | Create Django App

### ISSUE THREAD

**Issue by jakjarvis** [jakjarvis/dream-itinerary#1]
Probably only need a single App to begin with, perhaps 'Trips'?

Maybe later we could include Wishlist as a seperate App, or as a different model within Trips.

**Comment by apoorvthedude** [comment]
Hi @jakjarvis, Can I solve this issue?
Please,elaborate about this issue little bit in depth.

**Comment by jakjarvis** [comment]
Hi @apoorvthedude , thanks for reaching out - actually this is really just a project for me and my friend to learn about Django and React, we're not really ready to collaborate more widely until we know a bit more about what we're doing. Honestly I didn't know these issues were visible publicly!

**Comment by apoorvthedude** [comment]
Okay
